### ISSUE TITLE
Criar design da página Sobre

### ISSUE THREAD

**Issue by aridanpantoja** [linkjr-castanhal/linkjr#13]
Como usuário, quero acessar a página “sobre” do site e encontrar as informações como estatísticas da empresa, time e informações essenciais sobre a LinkJr de forma clara e organizada, para entender de forma mais profunda o propósito da empresa.

**Critérios importantes:**

1. A página deve incluir a Navbar
2. Apresentar uma introdução clara sobre a empresa.
3. Exibir números importantes que destaquem os resultados ou impacto (ex.: clientes atendidos, projetos realizados, anos de experiência).
4. Mostrar informações sobre os colaboradores principais com foto, nome, cargo e uma breve descrição.
5. A página deve incluir o FAQ
6. A página deve incluir o CTA
7. A página deve incluir o Footer
8. Layout responsivo para dispositivos desktop, tablet e mobile

<sub><a href="https://huly.app/guest/linkjr?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkZmUzN2QyZWY0Y2JjYzQ2ZDcxMTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbGlua2pyY2FzdGFuLWxpbmtqci02NzBiNDcyNS0wMzVjZTM3MDEzLTYxYTg4NSJ9.eJSzHVIbiuN_agQQvEpx-7rIgEK83Ch9l-zNS5A2Opg">Huly&reg;: <b>LNK-14</b></a></sub>

**Comment by kwojtyla** [comment]
Task finalizada, aguardando review pra mover pra Done.

[Sarah Cabral](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=6711af48217f601ab9fbd495&label=Sarah%20Cabral) [Aridan Pantoja](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=6716b693b8d2424eeafe931b&label=Aridan%20Pantoja) [Leandro Félix](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=671189c8b2083f7e4fb7153b&label=Leandro%20F%C3%A9lix)
