### ISSUE TITLE
Criar design de Vagas

### ISSUE THREAD

**Issue by ghost** [linkjr-castanhal/linkjr#19]
<sub><a href="https://huly.app/guest/linkjr?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUxZmVmM2QyZWY0Y2JjYzQ2ZjJjN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbGlua2pyY2FzdGFuLWxpbmtqci02NzBiNDcyNS0wMzVjZTM3MDEzLTYxYTg4NSJ9.nrq6LkzmK3kOTkxpTBskz9WtGHy31adam7Q7fdxbwEk">Huly&reg;: <b>LNK-20</b></a></sub>

**Comment by kwojtyla** [comment]
Finalizada a página de vagas geral no Figma. Podem revisar e dar o aval pra colocar como Ready for Dev?

[Aridan Pantoja](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=6716b693b8d2424eeafe931b&label=Aridan%20Pantoja) 

[Leandro Félix](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=67341770067c5e54870403b2&label=Leandro%20F%C3%A9lix) 

[Sarah Cabral](https://huly.app/browse/?workspace=w-linkjrcastan-linkjr-670b4725-035ce37013-61a885&_class=contact%3Aclass%3APerson&_id=6711af48217f601ab9fbd495&label=Sarah%20Cabral)
