### ISSUE TITLE
Criar função de modo claro/escuro

### ISSUE THREAD

**Issue by aridanpantoja** [linkjr-castanhal/linkjr#7]
Como um visitante do site, quero alternar entre os modos claro e escuro, para ajustar a aparência da interface às minhas preferências visuais e às condições de iluminação.

**Critérios importantes:**

1. O footer deve conter:
   * Deve haver um botão ou ícone visível na interface para alternar entre os modos claro e escuro.
   * O tema deve ser atualizado instantaneamente ao clicar no botão.

<sub><a href="https://huly.app/guest/linkjr?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ4YjBhYWQyZWY0Y2JjYzQ2YzNkYzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbGlua2pyY2FzdGFuLWxpbmtqci02NzBiNDcyNS0wMzVjZTM3MDEzLTYxYTg4NSJ9.mEJjAjItXT4L4hi9xqJyKiRMJhhgLgq0Wg8GW0zXqqk">Huly&reg;: <b>LNK-8</b></a></sub>

**Comment by ecsistem** [comment]
#14 Resolve
